version: '3'
services:
  db:
    container_name: containermysqlbbb
    image: mysql
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "33061:3306"
    networks:
      - dockernetworkbbb
    command: --default-authentication-plugin=mysql_native_password

  web:
    container_name: containerpythonslimbbb
    image: python:slim
    links:
      - db
    depends_on:
      - db
    working_dir: /code
    volumes:
      - ./requirements.txt:/code/requirements.txt
      - ./.env:/code/.env
      - ./app:/code/app
    networks:
      - dockernetworkbbb
    ports:
      - "8000:8000"
    command: bash -c "pip install --no-cache-dir -r /code/requirements.txt && python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: on-failure

networks:
  dockernetworkbbb:
    driver: bridge